project_id = "odwaaaewsffftmnomdvy"

[functions.save-ai-config]
verify_jwt = false

[functions.generate-ai-suggestions]
verify_jwt = false

[functions.generate-feedback]
verify_jwt = false

[functions.check-ai-config]
verify_jwt = false
